/** Machine-readable flow map — mirrors docs/COMPLETE_FLOW_MAP.md */

export type FlowLevel = "L0" | "L1" | "L2" | "L3" | "L4";

export interface FlowNode {
  id: string;
  level: FlowLevel;
  title: string;
  route?: string;
  action?: string;
  children?: FlowNode[];
}

export const PLATFORM_FLOWS: FlowNode[] = [
  {
    id: "public",
    level: "L0",
    title: "Public (unauthenticated)",
    children: [
      {
        id: "pub-home",
        level: "L1",
        title: "Homepage",
        route: "/",
        children: [
          { id: "pub-home-cta-learn", level: "L4", title: "CTA Start Learning", route: "/courses", action: "navigate" },
          { id: "pub-home-cta-teach", level: "L4", title: "CTA Start Teaching", route: "/auth/register", action: "navigate" },
          { id: "pub-home-program", level: "L4", title: "Program card", route: "/programs/[slug]", action: "navigate" },
        ],
      },
      {
        id: "pub-courses",
        level: "L1",
        title: "Course catalog",
        route: "/courses",
        children: [
          { id: "pub-courses-filter", level: "L3", title: "Search & filters", action: "filter state" },
          { id: "pub-courses-detail", level: "L2", title: "Course detail", route: "/courses/[slug]", children: [
            { id: "pub-enroll-free", level: "L4", title: "Enroll Free", route: "/learn/.../introduction", action: "enrollFree + navigate" },
            { id: "pub-add-cart", level: "L4", title: "Add to cart", route: "/cart", action: "cartStore.add" },
            { id: "pub-wishlist", level: "L4", title: "Wishlist toggle", action: "appStore.toggleWishlist" },
          ]},
        ],
      },
      {
        id: "pub-kits",
        level: "L1",
        title: "Learning kits catalog",
        route: "/kits",
        children: [
          { id: "pub-kits-filter", level: "L3", title: "Category & difficulty filters", action: "filter state" },
          { id: "pub-kits-detail", level: "L2", title: "Kit detail", route: "/kits/[slug]", children: [
            { id: "pub-kits-bom", level: "L4", title: "What's in the box tab", action: "view BOM" },
            { id: "pub-kits-materials", level: "L4", title: "Learning materials tab", action: "open material" },
            { id: "pub-kits-start", level: "L4", title: "Start learning with kit", action: "toast + workspace" },
            { id: "pub-kits-request", level: "L4", title: "Request kit for school", action: "org request" },
          ]},
        ],
      },
      {
        id: "pub-auth",
        level: "L1",
        title: "Authentication",
        children: [
          { id: "pub-login", level: "L2", title: "Login", route: "/auth/login", action: "authStore.login → /dashboard" },
          { id: "pub-register", level: "L2", title: "Register", route: "/auth/register", action: "→ /onboarding" },
          { id: "pub-onboard", level: "L2", title: "Onboarding (4 steps)", route: "/onboarding", action: "→ /dashboard" },
          { id: "pub-forgot", level: "L2", title: "Forgot password", route: "/auth/forgot-password" },
          { id: "pub-reset", level: "L2", title: "Reset password", route: "/auth/reset-password" },
        ],
      },
      {
        id: "pub-commerce",
        level: "L1",
        title: "Commerce",
        children: [
          { id: "pub-cart", level: "L2", title: "Cart", route: "/cart", action: "coupon UJUZI20" },
          { id: "pub-checkout", level: "L2", title: "Checkout", route: "/checkout", action: "pay → success/failed" },
        ],
      },
      {
        id: "pub-solutions",
        level: "L1",
        title: "IoT Solutions",
        route: "/solutions",
        children: [
          { id: "pub-solutions-filter", level: "L3", title: "Level & joined filters", action: "filter state" },
          { id: "pub-solutions-detail", level: "L2", title: "Solution workspace", route: "/solutions/[slug]", children: [
            { id: "pub-solutions-join", level: "L4", title: "Join solution", action: "joinSolution + toast" },
            { id: "pub-solutions-steps", level: "L4", title: "Build steps tab", action: "view instructions" },
            { id: "pub-solutions-kit", level: "L4", title: "Required kit link", route: "/kits/[slug]", action: "navigate" },
          ]},
        ],
      },
      {
        id: "pub-lab-resources",
        level: "L1",
        title: "Lab resources",
        route: "/lab-resources",
        children: [
          { id: "pub-lab-filter", level: "L3", title: "Hardware/Software/Dataset/API filters", action: "filter state" },
          { id: "pub-lab-detail", level: "L2", title: "Resource detail", route: "/lab-resources/[slug]", action: "download / docs link" },
        ],
      },
      {
        id: "pub-programs",
        level: "L1",
        title: "Programs & bootcamps",
        route: "/programs",
        children: [
          { id: "pub-programs-filter", level: "L3", title: "Type filter", action: "All/Bootcamp/Program/Incubator" },
          { id: "pub-programs-detail", level: "L2", title: "Program detail", route: "/programs/[slug]", action: "register (dashboard)" },
        ],
      },
      {
        id: "pub-projects",
        level: "L1",
        title: "Innovation projects",
        route: "/projects",
        children: [
          { id: "pub-projects-detail", level: "L2", title: "Project showcase", route: "/projects/[slug]", action: "support / view" },
        ],
      },
      {
        id: "pub-competitions",
        level: "L1",
        title: "Competitions",
        route: "/competitions",
        children: [
          { id: "pub-comp-detail", level: "L2", title: "Competition detail", route: "/competitions/[slug]", action: "register team" },
        ],
      },
      {
        id: "pub-orgs",
        level: "L1",
        title: "Partner organizations",
        route: "/organizations",
        children: [
          { id: "pub-org-detail", level: "L2", title: "Organization profile", route: "/organizations/[slug]", action: "view courses/programs" },
        ],
      },
      {
        id: "pub-community",
        level: "L1",
        title: "Community preview",
        route: "/community",
        children: [
          { id: "pub-community-channel", level: "L4", title: "Channel card", action: "login → dashboard channel" },
          { id: "pub-community-post", level: "L4", title: "Post teaser", action: "login → post detail" },
        ],
      },
      {
        id: "pub-blog",
        level: "L1",
        title: "Blog",
        route: "/blog",
        children: [
          { id: "pub-blog-post", level: "L2", title: "Article", route: "/blog/[slug]", action: "read" },
        ],
      },
      {
        id: "pub-utility",
        level: "L1",
        title: "Utility pages",
        children: [
          { id: "pub-search", level: "L2", title: "Global search", route: "/search", action: "courses, kits, programs, solutions" },
          { id: "pub-pricing", level: "L2", title: "Pricing", route: "/pricing" },
          { id: "pub-about", level: "L2", title: "About", route: "/about" },
          { id: "pub-contact", level: "L2", title: "Contact", route: "/contact", action: "form → toast" },
          { id: "pub-verify", level: "L2", title: "Verify certificate", route: "/verify-certificate" },
          { id: "pub-privacy", level: "L2", title: "Privacy", route: "/privacy" },
          { id: "pub-terms", level: "L2", title: "Terms", route: "/terms" },
        ],
      },
    ],
  },
  {
    id: "student",
    level: "L0",
    title: "Student portal",
    children: [
      {
        id: "stu-dash",
        level: "L1",
        title: "Dashboard",
        route: "/dashboard",
        children: [
          { id: "stu-resume", level: "L4", title: "Resume course", route: "/learn/[slug]/[lesson]", action: "navigate" },
          { id: "stu-streak", level: "L3", title: "Learning streak", action: "display" },
        ],
      },
      {
        id: "stu-learn",
        level: "L1",
        title: "Course player",
        route: "/learn/[courseSlug]/[lessonSlug]",
        children: [
          { id: "stu-video", level: "L3", title: "Video lesson", action: "play, mark complete, notes" },
          { id: "stu-quiz", level: "L3", title: "Quiz", action: "intro→active→result, pass/fail" },
          { id: "stu-assign", level: "L3", title: "Assignment", action: "upload, draft, submit" },
          { id: "stu-ai", level: "L4", title: "AI Mentor panel", action: "chat widget" },
        ],
      },
      {
        id: "stu-community",
        level: "L1",
        title: "Community",
        route: "/dashboard/community",
        children: [
          { id: "stu-channel", level: "L2", title: "Channel", route: "/dashboard/community/[slug]" },
          { id: "stu-post", level: "L2", title: "Post detail", route: "/dashboard/community/post/[id]" },
        ],
      },
      {
        id: "stu-programs",
        level: "L1",
        title: "Programs",
        route: "/dashboard/programs",
        children: [
          { id: "stu-program-register", level: "L4", title: "Register", action: "registerProgram" },
          { id: "stu-program-detail", level: "L4", title: "View details", route: "/programs/[slug]" },
        ],
      },
      {
        id: "stu-competitions",
        level: "L1",
        title: "Competitions",
        route: "/dashboard/competitions",
        children: [
          { id: "stu-comp-register", level: "L4", title: "Register team", action: "registerCompetition" },
        ],
      },
      {
        id: "stu-kits",
        level: "L1",
        title: "Learning kits",
        route: "/kits",
        children: [
          { id: "stu-kit-detail", level: "L2", title: "Kit detail", route: "/kits/[slug]", action: "BOM, materials, gallery" },
        ],
      },
      {
        id: "stu-settings",
        level: "L1",
        title: "Settings",
        children: [
          { id: "stu-settings-profile", level: "L2", title: "Profile", route: "/dashboard/settings/profile", action: "avatar upload mock" },
          { id: "stu-settings-account", level: "L2", title: "Account", route: "/dashboard/settings/account" },
          { id: "stu-settings-notif", level: "L2", title: "Notifications", route: "/dashboard/settings/notifications", action: "notificationPrefs persist" },
          { id: "stu-settings-billing", level: "L2", title: "Billing", route: "/dashboard/settings/billing" },
          { id: "stu-settings-privacy", level: "L2", title: "Privacy", route: "/dashboard/settings/privacy", action: "privacyPrefs persist" },
        ],
      },
      { id: "stu-wishlist", level: "L1", title: "Wishlist", route: "/dashboard/wishlist" },
      { id: "stu-certs", level: "L1", title: "Certificates", route: "/dashboard/certificates", children: [
        { id: "stu-cert-detail", level: "L2", title: "Certificate", route: "/dashboard/certificates/[certId]" },
      ]},
      { id: "stu-projects", level: "L1", title: "My projects", route: "/dashboard/projects", children: [
        { id: "stu-project-new", level: "L2", title: "New project", route: "/dashboard/projects/new" },
      ]},
    ],
  },
  {
    id: "instructor",
    level: "L0",
    title: "Instructor portal",
    children: [
      { id: "ins-dash", level: "L1", title: "Dashboard", route: "/instructor/dashboard" },
      { id: "ins-courses", level: "L1", title: "My courses", route: "/instructor/courses", children: [
        { id: "ins-builder", level: "L2", title: "Course builder (6 steps)", route: "/instructor/courses/new", action: "submit review; step 3 kit linking" },
        { id: "ins-edit", level: "L2", title: "Edit course", route: "/instructor/courses/[courseId]/edit" },
        { id: "ins-preview", level: "L2", title: "Preview", route: "/instructor/courses/[courseId]/preview" },
        { id: "ins-analytics", level: "L2", title: "Course analytics", route: "/instructor/courses/[courseId]/analytics" },
      ]},
      { id: "ins-analytics-global", level: "L1", title: "Analytics", route: "/instructor/analytics" },
      { id: "ins-earnings", level: "L1", title: "Earnings", route: "/instructor/earnings" },
      { id: "ins-students", level: "L1", title: "Students", route: "/instructor/students", children: [
        { id: "ins-student-detail", level: "L2", title: "Student progress", route: "/instructor/students/[studentId]" },
      ]},
      { id: "ins-grade", level: "L1", title: "Grade assignment", route: "/instructor/assignments/grade", action: "rubric + feedback" },
    ],
  },
  {
    id: "org",
    level: "L0",
    title: "Organization portal",
    children: [
      { id: "org-dash", level: "L1", title: "Overview", route: "/org/[slug]/dashboard" },
      { id: "org-members", level: "L1", title: "Members", route: "/org/[slug]/members", action: "invite, roles" },
      { id: "org-courses", level: "L1", title: "Courses", route: "/org/[slug]/courses", action: "manage assignment modal" },
      { id: "org-kits", level: "L1", title: "Learning kits inventory", route: "/org/[slug]/kits", children: [
        { id: "org-kit-request", level: "L4", title: "Request kits", action: "orgKitStore request form" },
        { id: "org-kit-inventory", level: "L4", title: "Update inventory", action: "on-hand / allocated" },
      ]},
      { id: "org-programs", level: "L1", title: "Programs", route: "/org/[slug]/programs" },
      { id: "org-competitions", level: "L1", title: "Competitions", route: "/org/[slug]/competitions" },
      { id: "org-analytics", level: "L1", title: "Analytics", route: "/org/[slug]/analytics", action: "export CSV" },
      { id: "org-settings", level: "L1", title: "Settings", route: "/org/[slug]/settings", action: "logo upload, SSO placeholder" },
    ],
  },
  {
    id: "mod",
    level: "L0",
    title: "Moderator",
    children: [
      { id: "mod-dash", level: "L1", title: "Queue overview", route: "/moderator" },
      { id: "mod-courses", level: "L1", title: "Course review", route: "/moderator/courses", action: "approve / reject modal" },
      { id: "mod-reports", level: "L1", title: "Content reports", route: "/moderator/reports" },
    ],
  },
  {
    id: "admin",
    level: "L0",
    title: "Super admin",
    children: [
      { id: "adm-dash", level: "L1", title: "KPI dashboard", route: "/admin" },
      { id: "adm-users", level: "L1", title: "Users", route: "/admin/users", children: [
        { id: "adm-user-detail", level: "L2", title: "User detail", route: "/admin/users/[userId]" },
      ]},
      { id: "adm-courses", level: "L1", title: "Courses", route: "/admin/courses" },
      { id: "adm-kits", level: "L1", title: "Learning kits", route: "/admin/kits", children: [
        { id: "adm-kit-new", level: "L2", title: "Create kit", route: "/admin/kits/new" },
        { id: "adm-kit-edit", level: "L2", title: "Kit editor (5 tabs)", route: "/admin/kits/[kitId]/edit", action: "BOM, materials, gallery, courses" },
      ]},
      { id: "adm-orgs", level: "L1", title: "Organizations", route: "/admin/organizations" },
      { id: "adm-payments", level: "L1", title: "Payments", route: "/admin/payments" },
      { id: "adm-mod", level: "L1", title: "Moderation hub", route: "/admin/moderation" },
      { id: "adm-analytics", level: "L1", title: "Analytics", route: "/admin/analytics" },
      { id: "adm-settings", level: "L1", title: "Platform settings", route: "/admin/settings" },
    ],
  },
];

export const ALL_ROUTES = [
  "/",
  "/courses",
  "/courses/[slug]",
  "/kits",
  "/kits/[slug]",
  "/programs",
  "/programs/[slug]",
  "/projects",
  "/projects/[slug]",
  "/competitions",
  "/competitions/[slug]",
  "/organizations",
  "/organizations/[slug]",
  "/community",
  "/pricing",
  "/about",
  "/contact",
  "/blog",
  "/blog/[slug]",
  "/verify-certificate",
  "/auth/login",
  "/auth/register",
  "/auth/forgot-password",
  "/auth/reset-password",
  "/onboarding",
  "/cart",
  "/checkout",
  "/checkout/success",
  "/checkout/failed",
  "/search",
  "/dashboard",
  "/dashboard/my-courses",
  "/dashboard/programs",
  "/dashboard/competitions",
  "/dashboard/community",
  "/dashboard/community/[channelSlug]",
  "/dashboard/community/post/[postId]",
  "/dashboard/resources",
  "/dashboard/organizations",
  "/dashboard/solutions",
  "/dashboard/projects",
  "/dashboard/projects/new",
  "/dashboard/certificates",
  "/dashboard/certificates/[certId]",
  "/dashboard/wishlist",
  "/dashboard/notifications",
  "/dashboard/settings/profile",
  "/dashboard/settings/account",
  "/dashboard/settings/notifications",
  "/dashboard/settings/billing",
  "/dashboard/settings/privacy",
  "/learn/[courseSlug]/[lessonSlug]",
  "/profile/[username]",
  "/instructor/dashboard",
  "/instructor/courses",
  "/instructor/courses/new",
  "/instructor/courses/[courseId]/edit",
  "/instructor/courses/[courseId]/preview",
  "/instructor/courses/[courseId]/analytics",
  "/instructor/analytics",
  "/instructor/earnings",
  "/instructor/students",
  "/instructor/students/[studentId]",
  "/instructor/assignments/grade",
  "/org/[slug]/dashboard",
  "/org/[slug]/members",
  "/org/[slug]/courses",
  "/org/[slug]/kits",
  "/org/[slug]/programs",
  "/org/[slug]/competitions",
  "/org/[slug]/analytics",
  "/org/[slug]/settings",
  "/moderator",
  "/moderator/courses",
  "/moderator/reports",
  "/admin",
  "/admin/users",
  "/admin/users/[userId]",
  "/admin/courses",
  "/admin/kits",
  "/admin/kits/new",
  "/admin/kits/[kitId]/edit",
  "/admin/organizations",
  "/admin/payments",
  "/admin/moderation",
  "/admin/analytics",
  "/admin/settings",
  "/flow-map",
  "/sitemap",
  "/solutions",
  "/solutions/[slug]",
  "/lab-resources",
  "/lab-resources/[slug]",
  "/privacy",
  "/terms",
] as const;
