import { S3Client, PutObjectCommand, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

const endpoint = process.env.B2_ENDPOINT;
const keyId = process.env.B2_KEY_ID;
const applicationKey = process.env.B2_APPLICATION_KEY;
const bucketName = process.env.B2_BUCKET_NAME;

const globalForStorage = globalThis as unknown as { storageClient?: S3Client };

function getClient() {
  if (!endpoint || !keyId || !applicationKey) {
    throw new Error("B2 storage is not configured (B2_ENDPOINT / B2_KEY_ID / B2_APPLICATION_KEY).");
  }
  if (!globalForStorage.storageClient) {
    // B2's S3-compatible endpoint embeds its region, e.g. s3.us-west-004.backblazeb2.com
    const region = new URL(endpoint).hostname.split(".")[1] ?? "us-west-004";
    globalForStorage.storageClient = new S3Client({
      region,
      endpoint,
      credentials: { accessKeyId: keyId, secretAccessKey: applicationKey },
    });
  }
  return globalForStorage.storageClient;
}

// Bucket stays private (Backblaze requires a card on file to enable public
// buckets). Files are instead served through /api/files/[...path], which
// redirects to a freshly signed URL generated by getSignedFileUrl below.
export async function uploadFile(key: string, body: Buffer, contentType: string): Promise<string> {
  if (!bucketName) {
    throw new Error("B2 storage is not configured (B2_BUCKET_NAME).");
  }

  await getClient().send(
    new PutObjectCommand({
      Bucket: bucketName,
      Key: key,
      Body: body,
      ContentType: contentType,
    })
  );

  return `/api/files/${key}`;
}

export async function getSignedFileUrl(key: string): Promise<string> {
  if (!bucketName) {
    throw new Error("B2 storage is not configured (B2_BUCKET_NAME).");
  }

  return getSignedUrl(getClient(), new GetObjectCommand({ Bucket: bucketName, Key: key }), {
    expiresIn: 300,
  });
}
